### ISSUE TITLE
Add F-Droid platform

### ISSUE THREAD

**Issue by toby3d** [w3c/manifest-app-info#24]
[F-Droid](https://f-droid.org/) has supported the distribution of open source application builds for the past 10 years. Perhaps we should include it in the [list of supported manifest platforms](https://github.com/w3c/manifest/wiki/Platforms)?

**Comment by aarongustafson** [comment]
@toby3d F-Droid looks like an app catalog as opposed to an app platform. Is that right?

**Comment by toby3d** [comment]
> @toby3d F-Droid looks like an app catalog as opposed to an app platform. Is that right?

I could be wrong, as I'm not in the mobile app development and distribution business, but no. It's not just a catalog of apps, but also a platform for delivering them, checking builds, and so on.

**Comment by aarongustafson** [comment]
> > F-Droid looks like an app catalog as opposed to an app platform. Is that right?
> 
> I could be wrong, as I'm not in the mobile app development and distribution business, but no. It's not just a catalog of apps, but also a platform for delivering them, checking builds, and so on.

As it is not an operating system, however, F-Droid isn’t really a candidate for use in `platform` because screenshots would not be different for that vs. another Android, for example.  We’re also going to be recommending authors use `platform` in a more generic sense (e.g., "narrow" vs. "wide") rather than using the specific platform on which the screenshot was taken. The OS-specific `platform` values should only be used if absolutely necessary (e.g., screenshot of a feature only available on ChromeOS).
